repos:
-   repo: local
    hooks:
    -   id: flake8
        name: Flake8
        description: This hook runs flake8 within our project's poetry environment.
        entry: poetry run flake8
        language: python
        types: [python]
        require_serial: true
